import Head from "next/head";
import LoginContent from "@contents/auth/login-content";

export default function Login() {
  return (
    <>
      <Head>
        <title>DUNA | LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginContent />
    </>
  );
}
