import DocsContent from "@contents/docs/docs-content";
import Head from "next/head";

export default function Members() {
  return (
    <>
      <Head>
        <title>DUNA - Documentations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DocsContent />
    </>
  );
}
