import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { getProject } from "@redux/actions/appData";
import ProjectPanel from "@contents/project-panel/project-panel";

export default function ProjectPanelId() {
  const router = useRouter();
  const projectId = router.query.projectId;
  const dispatch = useDispatch();
  const appUser = useSelector(state => state.appUser);
  const { project } = useSelector(state => state.appData);
  // console.log("[project-Panel/]: ", project);

  useEffect(() => {
    // let foundProject = projects ? projects.find(project => project.id === projectId) : undefined;
    // foundProject && setProject(foundProject);
    // foundProject && console.log(foundProject);
    if (appUser && appUser.id) {
      dispatch(getProject(projectId));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, appUser]);

  return (
    <>
      <Head>
        <title>DUNA - Member Area - {project?.title || "Project"} </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProjectPanel project={project} />
    </>
  );
}
