import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getProfileEvaluations, getProfileProjects, getProfileRounds } from "@redux/actions/appUserData";
import DashboardArchitect from "@contents/dashboard/dashboard-architect";

export default function RoundPanelPage() {
  const dispatch = useDispatch();
  const appUser = useSelector(state => state.appUser);
  const appUserData = useSelector(state => state.appUserData);

  // useEffect(() => {
  //   console.log("[members:projects]", projects);
  // }, [user, projects]);

  useEffect(() => {
    console.log("[members:data]");
    if (appUser && appUser.id) {
      dispatch(getProfileProjects(appUser.id));
      dispatch(getProfileRounds(appUser.id));
      dispatch(getProfileEvaluations(appUser.id));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [appUser]);

  let dashboard = null;
  if (appUser) {
    switch (appUser.type) {
      case "client":
        // dashboard = <DashboardClient appUser={appUser} projects={projects} />;
        break;

      case "architect":
        dashboard = <DashboardArchitect appUser={appUser} appUserData={appUserData} />;
        break;

      case "office":
        // dashboard = <DashboardOffice appUser={appUser} projects={projects} />;
        break;

      default:
        break;
    }
  }

  return (
    <>
      <Head>
        <title>DUNA - Member Area - {appUser.type || "Architect"} Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {dashboard}
    </>
  );
}
