import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
// import { getProfileEvaluations, getProfileProjects, getProfileRounds } from "@redux/actions/appUserData";
import { getProfileProjects } from "@redux/actions/appUserData";
import ProjectsPortfolio from "contents/projects-portfolio/projects-portfolio";

export default function ProjectsPortfolioPage() {
  const dispatch = useDispatch();
  const appUser = useSelector(state => state.appUser);
  const appUserData = useSelector(state => state.appUserData);

  // useEffect(() => {
  //   console.log("[members:projects]", projects);
  // }, [user, projects]);

  useEffect(() => {
    console.log("[members:data]");
    if (appUser && appUser.id) {
      dispatch(getProfileProjects(appUser.id));
      // dispatch(getProfileRounds(appUser.id));
      // dispatch(getProfileEvaluations(appUser.id));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [appUser]);

  return (
    <>
      <Head>
        <title>DUNA - Member Area - Projects Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProjectsPortfolio appUserData={appUserData} />
    </>
  );
}
