import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getRound } from "@redux/actions/appData";
import RoundPanel from "@contents/round-panel/round-panel";

export default function RoundPage() {
  const router = useRouter();
  const dispatch = useDispatch();
  // const { rounds } = useSelector(state => state.appUserData);
  const { round } = useSelector(state => state.appData);
  const roundDate = router.query.date;

  useEffect(() => {
    dispatch(getRound("undefined", roundDate));
    // console.log(router.query.date);
    // ** to be added : for PANEL components, user check is necessary.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [roundDate]);

  return (
    <>
      <Head>
        <title>DUNA - Member Area - Round</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <RoundPanel round={round} />
    </>
  );
}
