import Head from "next/head";
// import { useRouter } from "next/router";

export default function Home() {
  // const router = useRouter();

  return (
    <div>
      <Head>
        <title>DUNA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ textAlign: "center", marginTop: "60px" }}>DUNA landing page</h1>
    </div>
  );
}

// ** server side solution to redirect wildcards (subdomains)
export async function getServerSideProps(context) {
  const hostnamePart1 = context.req.headers.host.split(".")[0];
  const hostnamePart2 = context.req.headers.host.split(".")[1];

  const wildcard =
    hostnamePart1 === "duna" || hostnamePart1 === "localhost" || hostnamePart1 === "localhost:3000"
      ? undefined
      : hostnamePart1;

  if (wildcard) {
    let dest = "/";
    if (hostnamePart2 === "duna") dest = `https://duna.archi/${hostnamePart1}`;
    if (hostnamePart2.split(":")[0] === "localhost") dest = `http://localhost:3000/${hostnamePart1}`;

    return {
      // props: { wildcard },
      redirect: {
        permanent: true,
        destination: dest,
      },
    };
  }

  return {};
  // return { props: { wildcard } };
  // wildcard =
  //   wildcard != "yourdomain" ? (process.env.NODE_ENV != "development" ? wildcard : process.env.TEST_WILDCARD) : "home";
}
